
package readservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Transactions", targetNamespace = "http://readservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Transactions {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns readservice.TransactionGroup
     */
    @WebMethod
    @WebResult(name = "GroupOfTransaction", partName = "GroupOfTransaction")
    @Action(input = "http://readservice/Transactions/findAllByUserDateRequest", output = "http://readservice/Transactions/findAllByUserDateResponse")
    public TransactionGroup findAllByUserDate(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
