
package soapwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CallOperationService", targetNamespace = "http://soapwebservice/", wsdlLocation = "http://localhost:3030/operations?wsdl")
public class CallOperationService
    extends Service
{

    private final static URL CALLOPERATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALLOPERATIONSERVICE_EXCEPTION;
    private final static QName CALLOPERATIONSERVICE_QNAME = new QName("http://soapwebservice/", "CallOperationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3030/operations?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALLOPERATIONSERVICE_WSDL_LOCATION = url;
        CALLOPERATIONSERVICE_EXCEPTION = e;
    }

    public CallOperationService() {
        super(__getWsdlLocation(), CALLOPERATIONSERVICE_QNAME);
    }

    public CallOperationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALLOPERATIONSERVICE_QNAME, features);
    }

    public CallOperationService(URL wsdlLocation) {
        super(wsdlLocation, CALLOPERATIONSERVICE_QNAME);
    }

    public CallOperationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALLOPERATIONSERVICE_QNAME, features);
    }

    public CallOperationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CallOperationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CallOperation
     */
    @WebEndpoint(name = "CallOperationPort")
    public CallOperation getCallOperationPort() {
        return super.getPort(new QName("http://soapwebservice/", "CallOperationPort"), CallOperation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CallOperation
     */
    @WebEndpoint(name = "CallOperationPort")
    public CallOperation getCallOperationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapwebservice/", "CallOperationPort"), CallOperation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALLOPERATIONSERVICE_EXCEPTION!= null) {
            throw CALLOPERATIONSERVICE_EXCEPTION;
        }
        return CALLOPERATIONSERVICE_WSDL_LOCATION;
    }

}
